### ISSUE TITLE
Preserve commit messages

### ISSUE THREAD

**Issue by lencioni** [noahsug/dominium#2]
I noticed that when I used dominium to split up a commit that I had written a nice commit message for, it didn't use my commit message in the split up bits. It would be nice if this was preserved. The body of the commit message might be a good place to include more detailed information about how the commit was split up via this tool.

**Comment by noahsug** [comment]
Good catch! It was only preserving the first line of the commit message. I've pushed v0.2.3 which fixes the issue.
