### ISSUE TITLE
0.2.3 does not have a dist directory

### ISSUE THREAD

**Issue by lencioni** [noahsug/dominium#3]
So it fails with this error message when trying to install it:

```
ENOENT: no such file or directory, chmod '/Users/joe_lencioni/.nvm/versions/node/v8.9.1/lib/node_modules/dominium/dist/cli.js'
This is related to npm not being able to find a file.
```

https://unpkg.com/dominium@0.2.3/

**Comment by lencioni** [comment]
Same problem with 0.2.4 https://unpkg.com/dominium@0.2.4/

**Comment by noahsug** [comment]
Somehow changing `"main": "src/run.js"` to `"main": "dist/cli.js"` fixed the issue. Latest version should now work.

**Comment by lencioni** [comment]
Thanks, it looks like we are back in business!
